stages:
  - build

build-jar:
  stage: build
  image: jruby:9.4.14.0
  tags:
    - linux
    - docker
  before_script:
    - apt-get update && apt-get install -y git ca-certificates
    - update-ca-certificates
    - gem install rake
    - mkdir -p config dist
    - echo "$WARBLE_CONFIG" > config/warble.rb
  script:
    - bundle install
    - bundle exec rake jar
    - VERSION=${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}
    - 'curl --fail --verbose --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file dist/tapsoob.jar "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/tapsoob/${VERSION}/tapsoob-${VERSION}.jar"'