stages:
  - build

build-jar:
  stage: build
  image: jruby:9.4.14.0
  tags:
    - linux
    - docker
  before_script:
    - apt-get update && apt-get install -y git ca-certificates
    - update-ca-certificates
    - gem install rake
    - mkdir -p config
    - echo "$WARBLE_CONFIG" > config/warble.rb
  script:
    - bundle install
    - bundle exec rake jar
    - mv dist/tapsoob.jar dist/tapsoob-${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}.jar
  artifacts:
    paths:
      - dist/*.jar
    expire_in: 1 week